pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'NYSegmentedControl', '~> 1.0.7'
pod 'WMPageController', '~> 1.3.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'BFNavigationBarDrawer'
pod 'SDWebImage', '~> 3.7.5'
pod 'AMapLocation'
